// AUTO-GENERATED by scripts/export-landing-example.mts — do not hand-edit the
// EXAMPLE_SCAN value. Re-run the script to refresh it from a saved proposal
// or accuracy-lab run:
//
//   DATABASE_URL=<url> npx tsx scripts/export-landing-example.mts "97th"
//
// Source: accuracy-lab run cmrqmy21j0001hs35v7i60ovz [CORRECTED] (updated 2026-07-19T19:16:49.377Z), priced via proposal cmrtubh4y0001148ot95ho4c8 package "Pro Shield"

import type { Downspout, EditableLine, RoofStructure } from "@/lib/types";

export type ExampleScan = {
  /** Display label, e.g. "6232 97th Dr NE, Lake Stevens, WA". */
  address: string;
  eaves: EditableLine[];
  rakes: EditableLine[];
  downspouts: Downspout[];
  roofStructure?: RoofStructure;
  canvasPxPerFt?: number;
  /** Public asset path of the baked aerial photo (null = diagram only). */
  aerialUrl: string | null;
  stats: {
    eaveLF: number;
    downspoutCount: number;
    corners: number;
    stories: number;
  };
  /** Derived contract total of the source proposal, in cents. */
  estimateTotalCents: number;
};

export const EXAMPLE_SCAN: ExampleScan | null = {
  "address": "6232 97th Dr NE, Lake Stevens, WA 98258",
  "eaves": [
    {
      "id": "solar-eave-0",
      "kind": "eave",
      "points": [
        {
          "x": 283,
          "y": 476
        },
        {
          "x": 283,
          "y": 426
        }
      ]
    },
    {
      "id": "solar-eave-1",
      "kind": "eave",
      "points": [
        {
          "x": 257,
          "y": 426
        },
        {
          "x": 257,
          "y": 246
        }
      ]
    },
    {
      "id": "solar-eave-2",
      "kind": "eave",
      "points": [
        {
          "x": 257,
          "y": 246
        },
        {
          "x": 320,
          "y": 246
        }
      ]
    },
    {
      "id": "solar-eave-3",
      "kind": "eave",
      "points": [
        {
          "x": 434.4,
          "y": 217.4
        },
        {
          "x": 554,
          "y": 93
        }
      ]
    },
    {
      "id": "solar-eave-6",
      "kind": "eave",
      "points": [
        {
          "x": 640,
          "y": 184
        },
        {
          "x": 599,
          "y": 225
        }
      ]
    },
    {
      "id": "solar-eave-7",
      "kind": "eave",
      "points": [
        {
          "x": 560,
          "y": 265
        },
        {
          "x": 529,
          "y": 296
        }
      ]
    },
    {
      "id": "solar-eave-8",
      "kind": "eave",
      "points": [
        {
          "x": 496,
          "y": 375
        },
        {
          "x": 469,
          "y": 375
        }
      ]
    },
    {
      "id": "solar-eave-9",
      "kind": "eave",
      "points": [
        {
          "x": 469,
          "y": 375
        },
        {
          "x": 469,
          "y": 431
        }
      ]
    },
    {
      "id": "solar-eave-10",
      "kind": "eave",
      "points": [
        {
          "x": 469,
          "y": 431
        },
        {
          "x": 451,
          "y": 431
        }
      ]
    },
    {
      "id": "solar-eave-11",
      "kind": "eave",
      "points": [
        {
          "x": 451,
          "y": 431
        },
        {
          "x": 451,
          "y": 493
        }
      ]
    },
    {
      "id": "solar-eave-12",
      "kind": "eave",
      "points": [
        {
          "x": 451,
          "y": 493
        },
        {
          "x": 369,
          "y": 493
        }
      ]
    },
    {
      "id": "tier-eave-1",
      "kind": "eave",
      "points": [
        {
          "x": 434,
          "y": 421
        },
        {
          "x": 335,
          "y": 423
        }
      ]
    },
    {
      "id": "tier-eave-2",
      "kind": "eave",
      "points": [
        {
          "x": 383,
          "y": 490
        },
        {
          "x": 386,
          "y": 434
        }
      ]
    },
    {
      "id": "eave-1784395439806",
      "kind": "eave",
      "points": [
        {
          "x": 320,
          "y": 246
        },
        {
          "x": 320,
          "y": 210.9
        }
      ]
    },
    {
      "id": "eave-1784395494347",
      "kind": "eave",
      "points": [
        {
          "x": 320,
          "y": 210.9
        },
        {
          "x": 390.3,
          "y": 210.9
        }
      ]
    },
    {
      "id": "eave-1784395544109",
      "kind": "eave",
      "points": [
        {
          "x": 391.7,
          "y": 220.9
        },
        {
          "x": 378.5,
          "y": 220.9
        }
      ]
    },
    {
      "id": "eave-1784395548485",
      "kind": "eave",
      "points": [
        {
          "x": 378.5,
          "y": 220.9
        },
        {
          "x": 378.5,
          "y": 254.6
        }
      ]
    },
    {
      "id": "eave-1784395551351",
      "kind": "eave",
      "points": [
        {
          "x": 378.5,
          "y": 254.6
        },
        {
          "x": 317,
          "y": 256
        }
      ]
    },
    {
      "id": "eave-1784395575369",
      "kind": "eave",
      "points": [
        {
          "x": 317,
          "y": 256
        },
        {
          "x": 317,
          "y": 423.9
        }
      ]
    },
    {
      "id": "eave-1784395578309",
      "kind": "eave",
      "points": [
        {
          "x": 317,
          "y": 423.9
        },
        {
          "x": 335,
          "y": 423
        }
      ]
    },
    {
      "id": "eave-1784395608538",
      "kind": "eave",
      "points": [
        {
          "x": 422.9,
          "y": 218.3
        },
        {
          "x": 434.4,
          "y": 217.4
        }
      ]
    },
    {
      "id": "eave-1784395662478",
      "kind": "eave",
      "points": [
        {
          "x": 554,
          "y": 93
        },
        {
          "x": 572.6,
          "y": 110.6
        }
      ]
    },
    {
      "id": "eave-1784395667878",
      "kind": "eave",
      "points": [
        {
          "x": 572.6,
          "y": 110.6
        },
        {
          "x": 577.7,
          "y": 105.1
        }
      ]
    },
    {
      "id": "eave-1784395673130",
      "kind": "eave",
      "points": [
        {
          "x": 577.7,
          "y": 105.1
        },
        {
          "x": 624.6,
          "y": 148.6
        }
      ]
    },
    {
      "id": "eave-1784395688927",
      "kind": "eave",
      "points": [
        {
          "x": 624.6,
          "y": 148.6
        },
        {
          "x": 618,
          "y": 159
        }
      ]
    },
    {
      "id": "eave-1784395696969",
      "kind": "eave",
      "points": [
        {
          "x": 618,
          "y": 159
        },
        {
          "x": 643.1,
          "y": 181.6
        }
      ]
    },
    {
      "id": "eave-1784395698971",
      "kind": "eave",
      "points": [
        {
          "x": 643.1,
          "y": 181.6
        },
        {
          "x": 640,
          "y": 184
        }
      ]
    },
    {
      "id": "eave-1784395748886",
      "kind": "eave",
      "points": [
        {
          "x": 493,
          "y": 283
        },
        {
          "x": 530.7,
          "y": 243.3
        }
      ]
    },
    {
      "id": "eave-1784395786377",
      "kind": "eave",
      "points": [
        {
          "x": 530.7,
          "y": 243.3
        },
        {
          "x": 556.8,
          "y": 268.1
        }
      ]
    },
    {
      "id": "eave-1784395815977",
      "kind": "eave",
      "points": [
        {
          "x": 493,
          "y": 283
        },
        {
          "x": 493,
          "y": 338.7
        }
      ]
    }
  ],
  "rakes": [
    {
      "id": "solar-rake-0",
      "kind": "rake",
      "points": [
        {
          "x": 283,
          "y": 426
        },
        {
          "x": 257,
          "y": 426
        }
      ]
    },
    {
      "id": "solar-rake-1",
      "kind": "rake",
      "points": [
        {
          "x": 320,
          "y": 246
        },
        {
          "x": 320,
          "y": 211
        }
      ]
    },
    {
      "id": "solar-rake-2",
      "kind": "rake",
      "points": [
        {
          "x": 320,
          "y": 211
        },
        {
          "x": 437,
          "y": 211
        }
      ]
    },
    {
      "id": "solar-rake-3",
      "kind": "rake",
      "points": [
        {
          "x": 599,
          "y": 225
        },
        {
          "x": 560,
          "y": 265
        }
      ]
    },
    {
      "id": "solar-rake-4",
      "kind": "rake",
      "points": [
        {
          "x": 369,
          "y": 476
        },
        {
          "x": 283,
          "y": 476
        }
      ]
    }
  ],
  "downspouts": [
    {
      "id": "ds-corner-1",
      "x": 257,
      "y": 426,
      "heightFt": 20
    },
    {
      "id": "ds-corner-2",
      "x": 257,
      "y": 246,
      "heightFt": 20
    },
    {
      "id": "ds-corner-3",
      "x": 554,
      "y": 93,
      "heightFt": 20
    },
    {
      "id": "ds-corner-4",
      "x": 451,
      "y": 493,
      "heightFt": 20
    },
    {
      "id": "ds-corner-5",
      "x": 369,
      "y": 493,
      "heightFt": 20
    },
    {
      "id": "ds-corner-6",
      "x": 640,
      "y": 184,
      "heightFt": 20
    },
    {
      "id": "ds-corner-7",
      "x": 469,
      "y": 431,
      "heightFt": 20
    },
    {
      "id": "ds-corner-8",
      "x": 496,
      "y": 375,
      "heightFt": 20
    },
    {
      "id": "ds-mid-solar-eave-1",
      "x": 257,
      "y": 336,
      "heightFt": 20
    },
    {
      "id": "ds-mid-solar-eave-3",
      "x": 496,
      "y": 152,
      "heightFt": 20
    },
    {
      "id": "ds-1784395848044",
      "x": 317,
      "y": 393.2,
      "heightFt": 20
    },
    {
      "id": "ds-1784395856602",
      "x": 337.3,
      "y": 210.9,
      "heightFt": 20
    }
  ],
  "roofStructure": {
    "perimeter": [
      {
        "x": 283,
        "y": 476
      },
      {
        "x": 283,
        "y": 426
      },
      {
        "x": 257,
        "y": 426
      },
      {
        "x": 257,
        "y": 246
      },
      {
        "x": 320,
        "y": 246
      },
      {
        "x": 320,
        "y": 211
      },
      {
        "x": 437,
        "y": 211
      },
      {
        "x": 554,
        "y": 93
      },
      {
        "x": 596,
        "y": 115
      },
      {
        "x": 640,
        "y": 184
      },
      {
        "x": 529,
        "y": 296
      },
      {
        "x": 529,
        "y": 316
      },
      {
        "x": 496,
        "y": 316
      },
      {
        "x": 496,
        "y": 375
      },
      {
        "x": 469,
        "y": 375
      },
      {
        "x": 469,
        "y": 431
      },
      {
        "x": 451,
        "y": 431
      },
      {
        "x": 451,
        "y": 493
      },
      {
        "x": 369,
        "y": 493
      },
      {
        "x": 369,
        "y": 476
      }
    ],
    "ridges": [
      {
        "id": "solar-ridge-0",
        "kind": "ridge",
        "label": "RIDGE",
        "points": [
          {
            "x": 388,
            "y": 308
          },
          {
            "x": 576,
            "y": 113
          }
        ]
      },
      {
        "id": "solar-ridge-1",
        "kind": "ridge",
        "label": "RIDGE",
        "points": [
          {
            "x": 350,
            "y": 433
          },
          {
            "x": 343,
            "y": 259
          }
        ]
      },
      {
        "id": "solar-ridge-2",
        "kind": "ridge",
        "label": "RIDGE",
        "points": [
          {
            "x": 509,
            "y": 363
          },
          {
            "x": 398,
            "y": 373
          }
        ]
      },
      {
        "id": "solar-ridge-3",
        "kind": "ridge",
        "label": "RIDGE",
        "points": [
          {
            "x": 542,
            "y": 208
          },
          {
            "x": 454,
            "y": 293
          }
        ]
      },
      {
        "id": "solar-ridge-4",
        "kind": "ridge",
        "label": "RIDGE",
        "points": [
          {
            "x": 463,
            "y": 278
          },
          {
            "x": 466,
            "y": 342
          }
        ]
      },
      {
        "id": "solar-ridge-5",
        "kind": "ridge",
        "label": "RIDGE",
        "points": [
          {
            "x": 333,
            "y": 287
          },
          {
            "x": 411,
            "y": 283
          }
        ]
      },
      {
        "id": "solar-ridge-6",
        "kind": "ridge",
        "label": "RIDGE",
        "points": [
          {
            "x": 593,
            "y": 254
          },
          {
            "x": 514,
            "y": 223
          }
        ]
      },
      {
        "id": "solar-ridge-7",
        "kind": "ridge",
        "label": "RIDGE",
        "points": [
          {
            "x": 392,
            "y": 290
          },
          {
            "x": 402,
            "y": 220
          }
        ]
      },
      {
        "id": "solar-ridge-8",
        "kind": "ridge",
        "label": "RIDGE",
        "points": [
          {
            "x": 560,
            "y": 256
          },
          {
            "x": 490,
            "y": 314
          }
        ]
      },
      {
        "id": "solar-ridge-9",
        "kind": "ridge",
        "label": "RIDGE",
        "points": [
          {
            "x": 426,
            "y": 360
          },
          {
            "x": 422,
            "y": 418
          }
        ]
      },
      {
        "id": "solar-ridge-10",
        "kind": "ridge",
        "label": "RIDGE",
        "points": [
          {
            "x": 545,
            "y": 109
          },
          {
            "x": 600,
            "y": 143
          }
        ]
      }
    ],
    "valleys": [],
    "confidence": 0.92
  },
  "canvasPxPerFt": 4.532923076923077,
  "aerialUrl": "/landing/example-aerial.jpg",
  "stats": {
    "eaveLF": 369,
    "downspoutCount": 12,
    "corners": 9,
    "stories": 2
  },
  "estimateTotalCents": 585619
};
